me: server3
host_address: "localhost:3312"
raft_config:
  server1: "localhost:3309"
  server2: "localhost:3311"
  server3: "localhost:3313"
persistence:
  persistent_file: "persist3.raft"
  persist_threshold: 1024
  snapshot_file: "snapshot3.kv"